import { Cinzel, Gotu, Inter } from "next/font/google";
import "./globals.css";

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel",
});

const gotu = Gotu({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-gotu",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${cinzel.variable} ${gotu.variable} ${inter.variable}`}>
        {children}
      </body>

    </html>
  );
}
